SELECT *
FROM(
	SELECT *,
		CASE
			WHEN [DETALLE PAGO PERMANENCIA] = [WEBI POSPAGO PERMANENCIA] AND [WEBI POSPAGO PERMANENCIA]=[WEBI POSPAGO PORCT PERMANENCIA] THEN 'OK'
			ELSE 'NO TIENEN LA MISMA PERMANENCIA'
		END AS 'VALIDACION'
	FROM(
		SELECT 
			DP.#ID_CONTRATO,
			DP.PERMANENCIA AS [DETALLE PAGO PERMANENCIA],
			DBP.[WEBI POSPAGO PERMANENCIA],
			DBPP.[WEBI POSPAGO PORCT PERMANENCIA],
			DP.semana
		FROM Detalle_Pago_Permanencia_Pospago DP
		LEFT JOIN (
			SELECT 
				[DISTRIBUIDOR SEC],
				COUNT([NUM CUENTA]) AS [WEBI POSPAGO PERMANENCIA]
			FROM Detalle_Bonos_Permanencia_WEBI
			GROUP BY [DISTRIBUIDOR SEC]
		) DBP ON DP.#ID_CONTRATO = DBP.[DISTRIBUIDOR SEC]
		LEFT JOIN (
			SELECT 
				[ID DISTRIBUIDOR],
				PERMANENCIA AS  [WEBI POSPAGO PORCT PERMANENCIA]
			FROM Detalle_Bonos_Permanencia_porcentaje_WEBI
		) DBPP ON DP.#ID_CONTRATO = DBPP.[ID DISTRIBUIDOR]) as A) AS AB
WHERE SEMANA ='Semana del 20 al 26 de 05-2024'
ORDER BY 2 DESC

